### ISSUE TITLE
YouTube cards

### ISSUE THREAD

**Issue by PixelRobots** [DenverCoder1/DenverCoder1#5]
Hi, I love what you have done with the YouTube cards and would like to do the same. Can you help when I follow what you have done I get an error.

**Comment by DenverCoder1** [comment]
Hi, sorry for not responding sooner.

At the time, I intended for the cards to only work on my own profile for a few reasons including that it uses the YouTube API which can get expensive if it gets a lot of traffic.

I have come up with a new solution which does not require the use of the YouTube API directly and eventually decided I'm fine with sharing this project with the world.

I've done almost a complete rewrite to enable the capabilities I think it should have and it is now published at <https://github.com/DenverCoder1/github-readme-youtube-cards>.

You can use the workflow specifically written for the purpose, but with proper parameters and date format settings, it should also be possible with gautamkrishnar's blog-post-workflow. Note that the public version requires you to pass the video id, video title, and unix timestamp of publication as URL parameters to <https://ytcards.demolab.com/>. Due to URLs requiring certain encoding to be valid, the [DenverCoder1/github-readme-youtube-cards](https://github.com/DenverCoder1/github-readme-youtube-cards) workflow will likely be more reliable.

Feel free to try it out if you're still interested and let me know what you think or if there are any issues!

**Comment by PixelRobots** [comment]
Hello, thanks for this. I am trying to set it up, but it seems to be having issues running the action. 
![image](https://user-images.githubusercontent.com/22979170/189374156-d590c41f-9995-4084-a742-20013367075f.png)
I also noticed the examples on the repo are not working too.
